#!/bin/bash


#############################################################################################
#											  			 								    #
#  System_secCheck									    									#
#  ----------------									    									#
#  Author: Marcin Radaszewski								    							#
#  GitHub   : https://github.com/							    							#
#  "System_secCheck" comes with ABSOLUTELY NO WARRANTY. This is free software, and you are  #
#  welcome to redistribute it under the terms of the GNU General Public License.	    	#
#  											    											#	
#############################################################################################


LINE="--------------------------------------"
OK="[\033[32mOK\e[0m]"
WAIT="[\033[32m*\e[0m]"
CHECKDIR="[\033[32mCHECK\e[0m]"
WAR="[\033[31m!\e[0m]"
INFO="[\033[34mINFO\e[0m]"
INFOW="[\033[31mINFO\e[0m]"

HEADER() {
echo ""
echo -e "----------- $1 $2  ------------" 
echo ""
}

DEBUG() {
echo -e $1 $2
}

CHECKSUM(){
echo $(du -sh $1 2>/dev/null |awk '{print $1}' | sha1sum | awk '{print $1}') $1 >> log          
}

./SYSTEM_INFO.sh
./DIR_CHECK.sh
# ./FIND_HIDDEN_FILE.sh
./NETWORK_CHECK.sh


